=== madhukiranpinnu/RestFramework/src/test/resources/jsons/Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "first_name": {
      "type": "string"
    },
    "last_name": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "jobs": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "food": {
      "type": "object",
      "properties": {
        "breakfast": {
          "type": "string"
        },
        "lunch": {
          "type": "string"
        },
        "dinner": {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "required": [
        "breakfast",
        "lunch",
        "dinner"
      ]
    }
  },
  "required": [
    "id",
    "first_name",
    "last_name",
    "email",
    "jobs",
    "food"
  ]
}

=== madhukiranpinnu/RestFramework/src/test/resources/output/Test2.json
{
    "id": "11289",
    "first_name": "granville",
    "last_name": "LEHNER",
    "email": "camelliaO'CONNELL@gmail.com",
    "jobs": [
        "tester",
        "shopkeeper"
    ],
    "food": {
        "breakfast": "idly",
        "lunch": "rice",
        "dinner": [
            "tester",
            "shopkeeper"
        ]
    }
}

=== madhukiranpinnu/RestFramework/src/test/resources/output/output.json
{
    "id": "16863",
    "first_name": "bao",
    "last_name": "ROWE",
    "email": "sherrilKOELPIN@gmail.com",
    "jobs": [
        "tester",
        "shopkeeper"
    ],
    "food": {
        "breakfast": "idly",
        "lunch": "rice",
        "dinner": [
            "tester",
            "shopkeeper"
        ]
    }
}

=== madhukiranpinnu/RestFramework/src/test/resources/output/Test3.json
{
    "id": "12994",
    "first_name": "chun",
    "last_name": "TORP",
    "email": "donnyWILL@gmail.com",
    "jobs": [
        "tester",
        "shopkeeper"
    ],
    "food": {
        "breakfast": "idly",
        "lunch": "rice",
        "dinner": [
            "tester",
            "shopkeeper"
        ]
    }
}
